### ISSUE TITLE
Requires happy and c2hs

### ISSUE THREAD

**Issue by lorenzo** [qwfy/doc-browser#1]
These 2 dependencies should be specified in the installation instructions.

Even after that I get the following error:

```
setup: The program 'moc' version >=5.0 && <6.0 is required but it could not be
    found.
```

Where can I find `moc`?

**Comment by lorenzo** [comment]
Ok, seems like I didn't link the binaries from the Qt installation, I found `moc`

**Comment by qwfy** [comment]
Thanks for the report :-) I have updated the installation instruction about happy and c2hs.

`moc` and other Qt stuff should be dealt with in a systematic way, I haven't looked into it yet.

**Comment by lorenzo** [comment]
Thanks!
