### ISSUE TITLE
Install docset form local file system

### ISSUE THREAD

**Issue by dontdieych** [qwfy/doc-browser#3]
Is it possible?

I've copied docset directory to ~/.config/doc-browser/Dash folder. But nothing happens.

**Comment by qwfy** [comment]
No, it will not work if just copy the files, there is some preprocessing involved.

Please refer to:

https://github.com/qwfy/doc-browser#install-dashs-docset

also:

https://github.com/qwfy/doc-browser#known-problems-and-solutions

**Comment by dontdieych** [comment]
So I'm wondered why my doc-browser complain about `--local-archive` flag does not valid...

And found couple of ours ago you committed new code :-)

It worked!
Thanks for quick response and code.
