### ISSUE TITLE
Support /usr/share/doc

### ISSUE THREAD

**Issue by xeruf** [qwfy/doc-browser#5]
There is a ton of valuable documentation under `/usr/share/doc`, but there seem to be no proper tools for accessing it:
https://askubuntu.com/questions/24072/how-are-typical-users-expected-to-read-the-documentation-in-usr-share-doc
Maybe a realm for this tool to consider?

**Comment by qwfy** [comment]
Hi, thanks for the thought.
 
`/usr/share/doc` is a valuable resource itself, and a nicer presentation would be better, I think the linux kernel calls fits right in, as for the CLI manuals, I'm less sure (a cookbook with short description would be more useful). Either way, I do not have the time required to implement and polish this.
